### ISSUE TITLE
Semi-circle Slider

### ISSUE THREAD

**Issue by melissaep** [vuedev-com/vue-circle-slider#12]
Are there props to change the slider from being a whole circle, to a 3/4 or half circle?

You can see an examples here: https://roundsliderui.com/demos.html#various-circle-shapes

(A similar question was asked here: https://github.com/devstark-com/vue-circle-slider/issues/11, but closed without any comments)

**Comment by Saymon-biz** [comment]
@melissaep no, this feature is not implemented for now
